/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOrganizerRouteImport } from './routes/_authenticated.organizer'
import { Route as AuthenticatedAttendeeRouteImport } from './routes/_authenticated.attendee'
import { Route as AuthenticatedOrganizerNewRouteImport } from './routes/_authenticated.organizer.new'
import { Route as AuthenticatedOrganizerSessionIdRouteImport } from './routes/_authenticated.organizer.$sessionId'
import { Route as AuthenticatedAttendeeScanRouteImport } from './routes/_authenticated.attendee.scan'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrganizerRoute = AuthenticatedOrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAttendeeRoute = AuthenticatedAttendeeRouteImport.update({
  id: '/attendee',
  path: '/attendee',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrganizerNewRoute =
  AuthenticatedOrganizerNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedOrganizerRoute,
  } as any)
const AuthenticatedOrganizerSessionIdRoute =
  AuthenticatedOrganizerSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedOrganizerRoute,
  } as any)
const AuthenticatedAttendeeScanRoute =
  AuthenticatedAttendeeScanRouteImport.update({
    id: '/scan',
    path: '/scan',
    getParentRoute: () => AuthenticatedAttendeeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/attendee': typeof AuthenticatedAttendeeRouteWithChildren
  '/organizer': typeof AuthenticatedOrganizerRouteWithChildren
  '/attendee/scan': typeof AuthenticatedAttendeeScanRoute
  '/organizer/$sessionId': typeof AuthenticatedOrganizerSessionIdRoute
  '/organizer/new': typeof AuthenticatedOrganizerNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/attendee': typeof AuthenticatedAttendeeRouteWithChildren
  '/organizer': typeof AuthenticatedOrganizerRouteWithChildren
  '/attendee/scan': typeof AuthenticatedAttendeeScanRoute
  '/organizer/$sessionId': typeof AuthenticatedOrganizerSessionIdRoute
  '/organizer/new': typeof AuthenticatedOrganizerNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/attendee': typeof AuthenticatedAttendeeRouteWithChildren
  '/_authenticated/organizer': typeof AuthenticatedOrganizerRouteWithChildren
  '/_authenticated/attendee/scan': typeof AuthenticatedAttendeeScanRoute
  '/_authenticated/organizer/$sessionId': typeof AuthenticatedOrganizerSessionIdRoute
  '/_authenticated/organizer/new': typeof AuthenticatedOrganizerNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/attendee'
    | '/organizer'
    | '/attendee/scan'
    | '/organizer/$sessionId'
    | '/organizer/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/attendee'
    | '/organizer'
    | '/attendee/scan'
    | '/organizer/$sessionId'
    | '/organizer/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/attendee'
    | '/_authenticated/organizer'
    | '/_authenticated/attendee/scan'
    | '/_authenticated/organizer/$sessionId'
    | '/_authenticated/organizer/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/organizer': {
      id: '/_authenticated/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof AuthenticatedOrganizerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendee': {
      id: '/_authenticated/attendee'
      path: '/attendee'
      fullPath: '/attendee'
      preLoaderRoute: typeof AuthenticatedAttendeeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizer/new': {
      id: '/_authenticated/organizer/new'
      path: '/new'
      fullPath: '/organizer/new'
      preLoaderRoute: typeof AuthenticatedOrganizerNewRouteImport
      parentRoute: typeof AuthenticatedOrganizerRoute
    }
    '/_authenticated/organizer/$sessionId': {
      id: '/_authenticated/organizer/$sessionId'
      path: '/$sessionId'
      fullPath: '/organizer/$sessionId'
      preLoaderRoute: typeof AuthenticatedOrganizerSessionIdRouteImport
      parentRoute: typeof AuthenticatedOrganizerRoute
    }
    '/_authenticated/attendee/scan': {
      id: '/_authenticated/attendee/scan'
      path: '/scan'
      fullPath: '/attendee/scan'
      preLoaderRoute: typeof AuthenticatedAttendeeScanRouteImport
      parentRoute: typeof AuthenticatedAttendeeRoute
    }
  }
}

interface AuthenticatedAttendeeRouteChildren {
  AuthenticatedAttendeeScanRoute: typeof AuthenticatedAttendeeScanRoute
}

const AuthenticatedAttendeeRouteChildren: AuthenticatedAttendeeRouteChildren = {
  AuthenticatedAttendeeScanRoute: AuthenticatedAttendeeScanRoute,
}

const AuthenticatedAttendeeRouteWithChildren =
  AuthenticatedAttendeeRoute._addFileChildren(
    AuthenticatedAttendeeRouteChildren,
  )

interface AuthenticatedOrganizerRouteChildren {
  AuthenticatedOrganizerSessionIdRoute: typeof AuthenticatedOrganizerSessionIdRoute
  AuthenticatedOrganizerNewRoute: typeof AuthenticatedOrganizerNewRoute
}

const AuthenticatedOrganizerRouteChildren: AuthenticatedOrganizerRouteChildren =
  {
    AuthenticatedOrganizerSessionIdRoute: AuthenticatedOrganizerSessionIdRoute,
    AuthenticatedOrganizerNewRoute: AuthenticatedOrganizerNewRoute,
  }

const AuthenticatedOrganizerRouteWithChildren =
  AuthenticatedOrganizerRoute._addFileChildren(
    AuthenticatedOrganizerRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAttendeeRoute: typeof AuthenticatedAttendeeRouteWithChildren
  AuthenticatedOrganizerRoute: typeof AuthenticatedOrganizerRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAttendeeRoute: AuthenticatedAttendeeRouteWithChildren,
  AuthenticatedOrganizerRoute: AuthenticatedOrganizerRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
